[package]
name = "libthere"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
color-eyre = { version = "0.6.2", features = ["issue-url"] }
derive-getters = "0.2.0"
serde = { version = "1.0.147", features = ["derive"] }
shell-words = "1.1.0"
tarpc = { version = "0.30.0", features = ["full"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.11"
tokio-util = { version = "0.7.4", features = ["codec"] }
tracing = { version = "0.1.37", features = ["async-await"] }
tracing-futures = { version = "0.2.5", features = ["tokio"] }
which = "4.3.0"
