[package]
name = "there-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libthere = { path = "../libthere" }

axum = "0.6.1"
color-eyre = { version = "0.6.2", features = ["issue-url"] }
futures = "0.3.25"
rand = "0.8.5"
thrussh = { version = "0.33.5", features = ["openssl"] }
thrussh-keys = { version = "0.21.0", features = ["openssl"] }
tokio = { version = "1.23.0", features = ["full"] }
network-interface = "0.1.6"
serde = { version = "1.0.152", features = ["derive"] }
quick_cache = "0.2.0"
nanoid = "0.4.0"
nanoid-dictionary = "0.4.3"
serde_json = "1.0.91"
hyper = "0.14.23"
tracing = "0.1.37"
thiserror = "1.0.38"
