[package]
name = "there-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
there = { path = "../libthere" }

axum = "0.6.16"
color-eyre = { version = "0.6.2", features = ["issue-url"] }
futures = "0.3.28"
rand = "0.8.5"
thrussh = { version = "0.33.5", features = ["openssl"] }
thrussh-keys = { version = "0.22.0", features = ["openssl"] }
tokio = { version = "1.27.0", features = ["full"] }
network-interface = "1.0.0"
serde = { version = "1.0.160", features = ["derive"] }
quick_cache = "0.2.4"
nanoid = "0.4.0"
nanoid-dictionary = "0.4.3"
serde_json = "1.0.96"
hyper = "0.14.26"
tracing = "0.1.37"
thiserror = "1.0.40"
tracing-subscriber = { version = "0.3.16", features = ["json", "time"] }
time = { version = "0.3.20", features = ["macros", "formatting"] }
