name: "Run clippy lints"
on:
  push:
    branches:
      - "mistress"
  pull_request:
    branches:
      - "mistress"

jobs:
  run-clippy:
    strategy:
      matrix:
        version: ["stable", "nightly", "1.64"]
    if: "github.actor != 'dependabot'"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install latest stable Rust"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "${{ matrix.version }}"
          override: true
          components: "clippy"
      - uses: "Swatinem/rust-cache@v1"
        with:
          key: "clippy"
      - name: "Run clippy"
        run: "cargo clippy"
