name: "Markdown lint"
on:
  push:
    branches:
    - "mistress"
    paths:
    - "**.md"
    - "README.md"
  pull_request:
    branches:
    - "mistress"
    paths:
    - "**.md"
    - "README.md"

jobs:
  lint-markdown:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Check out code"
      uses: actions/checkout@v2

    - name: "Lint all markdown"
      uses: "avto-dev/markdown-lint@v1"
      with:
        args: "src/**/*.md README.md"
